services:
  # Backend (Node.js + Express) service
  backend:
    image: prateekjaiswal16/mern-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    network:
      - environ
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  # Frontend (React) service
  frontend:
    image: prateekjaiswal16/mern-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    network:
      - environ
    environment:
      - REACT_APP_API_URL=backend
    depends_on:
      - backend

networks:
  environ: