version: '3.8'
services:
  # Backend (Node.js + Express) service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    network: host
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI=${MONGODB_URI}
      JWT_SECRET=${JWT_SECRET}

  # Frontend (React) service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    network: host
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: backend
    depends_on:
      - backend
